import { TTSVoice } from '../types/tts';
import puckImg from '../assets/images/ai_voice_puck_1789587497983.jpg';
import aoedeImg from '../assets/images/ai_voice_aoede_1789587510659.jpg';
import charonImg from '../assets/images/ai_voice_charon_1789587523989.jpg';
import koreImg from '../assets/images/ai_voice_kore_1789587535400.jpg';

export const ALL_30_GEMINI_VOICES: TTSVoice[] = [
  // 1
  {
    id: 'Puck',
    name: 'Puck',
    gender: 'male',
    arabicTitle: 'باك (Puck)',
    description: 'صوت شبابي مفعم بالحيوية، مرن ومريح للاستماع اليومي والمحادثات السريعة.',
    badge: 'حيوي وشبابي',
    avatarColor: 'from-cyan-500 to-blue-600',
    avatarUrl: puckImg,
    tone: 'حيوي',
    tags: ['بودكاست', 'حواري', 'يومي'],
  },
  // 2
  {
    id: 'Charon',
    name: 'Charon',
    gender: 'male',
    arabicTitle: 'شارون (Charon)',
    description: 'صوت عميق ورصين بنبرة وثائقية موثوقة تناسب الأخبار والشروحات الرسمية.',
    badge: 'عميق ورسمي',
    avatarColor: 'from-indigo-600 to-purple-700',
    avatarUrl: charonImg,
    tone: 'رصين',
    tags: ['وثائقي', 'إخباري', 'فصيح'],
  },
  // 3
  {
    id: 'Kore',
    name: 'Kore',
    gender: 'female',
    arabicTitle: 'كوري (Kore)',
    description: 'صوت أنثوي متوازن، نقي وواضح النطق ومناسب للكتب الصوتية والمحتوى التعليمي.',
    badge: 'نقي ومتوازن',
    avatarColor: 'from-rose-500 to-pink-600',
    avatarUrl: koreImg,
    tone: 'تعليمي',
    tags: ['كتب صوتية', 'تعليمي', 'واضح'],
  },
  // 4
  {
    id: 'Fenrir',
    name: 'Fenrir',
    gender: 'male',
    arabicTitle: 'فنرير (Fenrir)',
    description: 'صوت قوي وجذاب ذو حضور واثق، ممتاز للإعلانات والنصوص التحفيزية.',
    badge: 'قوي ومؤثر',
    avatarColor: 'from-amber-500 to-orange-600',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'تحفيزي',
    tags: ['إعلاني', 'حماسي', 'تسويق'],
  },
  // 5
  {
    id: 'Aoede',
    name: 'Aoede',
    gender: 'female',
    arabicTitle: 'أويدي (Aoede)',
    description: 'صوت أنثوي دافئ ولحني يوحي بالألفة والهدوء، رائع للبودكاست والتأمل.',
    badge: 'دافئ ولحني',
    avatarColor: 'from-emerald-500 to-teal-600',
    avatarUrl: aoedeImg,
    tone: 'دافئ',
    tags: ['تأمل', 'قصصي', 'مريح'],
  },
  // 6
  {
    id: 'Zephyr',
    name: 'Zephyr',
    gender: 'female',
    arabicTitle: 'زفير (Zephyr)',
    description: 'نبرة هادئة ورقيقة كانسياب النسيم، مثالية للمساعدات الذكية والاسترخاء.',
    badge: 'ناعم وانسيابي',
    avatarColor: 'from-sky-400 to-cyan-500',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'هادئ',
    tags: ['مساعد ذكي', 'استرخاء', 'خفيف'],
  },
  // 7
  {
    id: 'Enceladus',
    name: 'Enceladus',
    gender: 'male',
    arabicTitle: 'إنسيلادوس (Enceladus)',
    description: 'صوت جهوري مصقول وواضح الحروف، يعطي فخامة للنصوص الأدبية الرفيعة.',
    badge: 'جهوري وفخم',
    avatarColor: 'from-blue-600 to-indigo-800',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'فخم',
    tags: ['أدبي', 'شعر', 'كلاسيكي'],
  },
  // 8
  {
    id: 'Achernar',
    name: 'Achernar',
    gender: 'female',
    arabicTitle: 'أخرنار (Achernar)',
    description: 'صوت أنثوي ساطع وحيوي، نبرة متفائلة تناسب الفيديوهات القصيرة والشروحات التفاعلية.',
    badge: 'ساطع ومتفائل',
    avatarColor: 'from-yellow-500 to-amber-600',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'مشرق',
    tags: ['سوشيال ميديا', 'ريلز', 'تفاعل'],
  },
  // 9
  {
    id: 'Achird',
    name: 'Achird',
    gender: 'male',
    arabicTitle: 'أخيرد (Achird)',
    description: 'صوت رجالي ودود ذو طابع قصصي يشد المستمع في الروايات والدراما الصوتية.',
    badge: 'راوي قصصي',
    avatarColor: 'from-teal-600 to-emerald-700',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'سردي',
    tags: ['روايات', 'قصص', 'تاريخ'],
  },
  // 10
  {
    id: 'Algenib',
    name: 'Algenib',
    gender: 'male',
    arabicTitle: 'الجناب (Algenib)',
    description: 'نبرة مهنية احترافية تشبه مذيعي الأخبار والقنوات الاقتصادية العالمية.',
    badge: 'مذيع إخباري',
    avatarColor: 'from-slate-600 to-slate-800',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'احترافي',
    tags: ['اقتصاد', 'أخبار', 'تقارير'],
  },
  // 11
  {
    id: 'Callirrhoe',
    name: 'Callirrhoe',
    gender: 'female',
    arabicTitle: 'كاليرهوي (Callirrhoe)',
    description: 'صوت شاعري رنان مع مخارج حروف عربية دقيقة جداً، يلائم الإلقاء المسرحي.',
    badge: 'شاعري معبر',
    avatarColor: 'from-fuchsia-500 to-purple-600',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'شاعري',
    tags: ['شعر فصيح', 'مسرحي', 'تعبير'],
  },
  // 12
  {
    id: 'Capella',
    name: 'Capella',
    gender: 'female',
    arabicTitle: 'العيوق (Capella)',
    description: 'نبرة لطيفة ومبهجة، ممتازة للتطبيقات التفاعلية وخدمة العملاء الآلية.',
    badge: 'لطيف ومبهج',
    avatarColor: 'from-pink-500 to-rose-600',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'ودود',
    tags: ['خدمة عملاء', 'تطبيقات', 'تفاعل'],
  },
  // 13
  {
    id: 'Despina',
    name: 'Despina',
    gender: 'female',
    arabicTitle: 'ديسبينا (Despina)',
    description: 'صوت تأملي عميق مع إيقاع هادئ يمنح السكينة وراحة البال عند الاستماع المطول.',
    badge: 'سكينة وتأمل',
    avatarColor: 'from-indigo-400 to-blue-500',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'تأملي',
    tags: ['استرخاء', 'تأمل', 'نوم'],
  },
  // 14
  {
    id: 'Dipper',
    name: 'Dipper',
    gender: 'male',
    arabicTitle: 'ديبر (Dipper)',
    description: 'نبرة عفوية وغير متكلفة تحاكي الأصدقاء، تناسب الحوارات واليوتيوب.',
    badge: 'عفوي وطبيعي',
    avatarColor: 'from-amber-600 to-yellow-700',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'عفوي',
    tags: ['يوتيوب', 'فلوجات', 'حوار'],
  },
  // 15
  {
    id: 'Eclipse',
    name: 'Eclipse',
    gender: 'female',
    arabicTitle: 'إكليبس (Eclipse)',
    description: 'نبرة سينمائية درامية ذات وقع مثير ومشوق، تلائم الإعلانات التشويقية للأفلام.',
    badge: 'سينمائي درامي',
    avatarColor: 'from-purple-800 to-slate-900',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'درامي',
    tags: ['سينما', 'تريلر', 'إثارة'],
  },
  // 16
  {
    id: 'Gacrux',
    name: 'Gacrux',
    gender: 'male',
    arabicTitle: 'جاكروكس (Gacrux)',
    description: 'صوت أكاديمي جاد ومستقر، مثالي للمحاضرات الجامعية والأوراق البحثية.',
    badge: 'أكاديمي جاد',
    avatarColor: 'from-stone-600 to-stone-800',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'أكاديمي',
    tags: ['محاضرات', 'أبحاث', 'جامعي'],
  },
  // 17
  {
    id: 'Iapetus',
    name: 'Iapetus',
    gender: 'male',
    arabicTitle: 'إيابيتوس (Iapetus)',
    description: 'نبرة حكيمة وهادئة تشبه صوت المفكرين، ملائمة للوثائقيات الفلسفية والتاريخية.',
    badge: 'حكيم وفلسفي',
    avatarColor: 'from-slate-700 to-indigo-900',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'حكيم',
    tags: ['فلسفة', 'تاريخ', 'سير ذاتية'],
  },
  // 18
  {
    id: 'Lyra',
    name: 'Lyra',
    gender: 'female',
    arabicTitle: 'قيثارة (Lyra)',
    description: 'صوت موسيقي ناعم كأوتار القيثارة، يبهر المستمع في النصوص الرومانسية والأدبية.',
    badge: 'موسيقي ناعم',
    avatarColor: 'from-violet-500 to-purple-600',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'موسيقي',
    tags: ['أدب', 'خواطر', 'بودكاست'],
  },
  // 19
  {
    id: 'Nova',
    name: 'Nova',
    gender: 'female',
    arabicTitle: 'نوفا (Nova)',
    description: 'صوت عصري مستقبلي مليء بالطاقة والذكاء، مناسب للشركات التقنية والـ SaaS.',
    badge: 'تقني حديث',
    avatarColor: 'from-cyan-400 to-blue-500',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'تقني',
    tags: ['ذكاء اصطناعي', 'تطبيقات', 'تقنية'],
  },
  // 20
  {
    id: 'Orbit',
    name: 'Orbit',
    gender: 'male',
    arabicTitle: 'أوربت (Orbit)',
    description: 'نبرة سريعة البديهة والوضوح، رائعة للبرامج الرياضية والتقارير الميدانية.',
    badge: 'ديناميكي سريع',
    avatarColor: 'from-blue-500 to-teal-600',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'ديناميكي',
    tags: ['رياضة', 'ميداني', 'سريع'],
  },
  // 21
  {
    id: 'Orion',
    name: 'Orion',
    gender: 'male',
    arabicTitle: 'الجبار (Orion)',
    description: 'صوت بطولي ملهم يملأ النفس ثقة وحماسة، رائع للمقدمات الملحمية والقيادية.',
    badge: 'بطولي وملهم',
    avatarColor: 'from-orange-600 to-red-700',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'ملهم',
    tags: ['قيادي', 'تحفيز', 'ملحمي'],
  },
  // 22
  {
    id: 'Pegasus',
    name: 'Pegasus',
    gender: 'male',
    arabicTitle: 'الفرس الأعظم (Pegasus)',
    description: 'نبرة مغامرة مبهجة تلهم الخيال في كتب الأطفال والمغامرات التفاعلية.',
    badge: 'مغامرة وخيال',
    avatarColor: 'from-emerald-600 to-cyan-700',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'خيالي',
    tags: ['أطفال', 'مغامرات', 'رسوم متحركة'],
  },
  // 23
  {
    id: 'Sulafat',
    name: 'Sulafat',
    gender: 'female',
    arabicTitle: 'السلحفاة (Sulafat)',
    description: 'صوت تنفيذي راقٍ يجمع بين الحزم والأناقة، ملائم للاجتماعات والعروض التقديمية.',
    badge: 'تنفيذي راقٍ',
    avatarColor: 'from-teal-500 to-emerald-600',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'تنفيذي',
    tags: ['شركات', 'عروض', 'رسمي'],
  },
  // 24
  {
    id: 'Umbriel',
    name: 'Umbriel',
    gender: 'male',
    arabicTitle: 'أمبریيل (Umbriel)',
    description: 'صوت جهوري غامض بنبرة ساحرة، يناسب روايات الخيال العلمي والغموض.',
    badge: 'غامض ومثير',
    avatarColor: 'from-purple-900 to-indigo-950',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'غامض',
    tags: ['خيال علمي', 'غموض', 'رعب'],
  },
  // 25
  {
    id: 'Ursa',
    name: 'Ursa',
    gender: 'female',
    arabicTitle: 'الدب الأكبر (Ursa)',
    description: 'نبرة أمومية دافئة تبعث الطمأنينة، مناسبة للإرشاد النفسي والنصائح الأسرية.',
    badge: 'حنون ومطمئن',
    avatarColor: 'from-rose-400 to-amber-500',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'حنون',
    tags: ['أسري', 'تربوي', 'إرشاد'],
  },
  // 26
  {
    id: 'Vega',
    name: 'Vega',
    gender: 'female',
    arabicTitle: 'النسر الواقع (Vega)',
    description: 'صوت بلوري النقاء فائق الوضوح في مخارج الحروف، ممتاز للدورات التفاعلية.',
    badge: 'بلوري ونقي',
    avatarColor: 'from-cyan-300 to-blue-600',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'نقي',
    tags: ['دورات', 'تدريب', 'وضوح'],
  },
  // 27
  {
    id: 'Vindemiatrix',
    name: 'Vindemiatrix',
    gender: 'female',
    arabicTitle: 'مقدم القِطاف (Vindemiatrix)',
    description: 'نبرة دبلوماسية رفيعة المستوى تتمتع بهدوء وجاذبية صوتية استثنائية.',
    badge: 'دبلوماسي هادئ',
    avatarColor: 'from-pink-600 to-purple-800',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'دبلوماسي',
    tags: ['دبلوماسي', 'مؤتمرات', 'خطاب'],
  },
  // 28
  {
    id: 'Zubenelgenubi',
    name: 'Zubenelgenubi',
    gender: 'male',
    arabicTitle: 'الزبانا الجنوبي (Zuben)',
    description: 'صوت موزون وموثوق يمنح المستمع شعوراً بالأمان والمصداقية في الشروحات.',
    badge: 'موثوق وموزون',
    avatarColor: 'from-emerald-700 to-slate-800',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'موثوق',
    tags: ['تعليم', 'قانوني', 'إرشادي'],
  },
  // 29
  {
    id: 'Sadalbari',
    name: 'Sadalbari',
    gender: 'female',
    arabicTitle: 'سعد البارع (Sadalbari)',
    description: 'صوت مشرق ومحبب ينبض بالتفاؤل، يلائم إعلانات الموضة والسفر واللايف ستايل.',
    badge: 'مشرق وعصري',
    avatarColor: 'from-amber-400 to-rose-500',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'مشرق',
    tags: ['لايف ستايل', 'سياحة', 'إعلانات'],
  },
  // 30
  {
    id: 'Castor',
    name: 'Castor',
    gender: 'male',
    arabicTitle: 'رأس التوأم (Castor)',
    description: 'نبرة تفاعلية تشاركية مريحة، مثالية للمحادثة الصوتية المستمرة وبناء الألفة.',
    badge: 'تشاركي وودود',
    avatarColor: 'from-indigo-500 to-cyan-600',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&h=400&q=80',
    tone: 'تشاركي',
    tags: ['محادثة', 'مساعد شخصي', 'ألعاب'],
  },
];
